
#ifndef HAL_IR_SENSOR_HANDLER_V1_IR_SENSOR_CFG_H_
#define HAL_IR_SENSOR_HANDLER_V1_IR_SENSOR_CFG_H_

#define SENSOR_PORT        PORT_A

#define LEFT_SENSOR_PIN     PIN_0
#define CENTER_SENSOR_PIN   PIN_1
#define RIGHT_SENSOR_PIN    PIN_2

#endif /* HAL_LCD_HANDLER_V1_LCD_CFG_H_ */
